version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE= user

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
